version: '2'
services:
  terraform:
    container_name: terraform
    build: .
    image: terraform-local
    volumes:
      - ../:/app
      - ${HOME}/.aws/credentials:/home/terraform/.aws/credentials:ro
      - ${HOME}/.aws/config:/home/terraform/.aws/config:ro
      - ${HOME}/.ssh/id_rsa.pub:/home/terraform/.ssh/id_rsa.pub:ro
      - ${HOME}/.ssh/id_rsa:/home/terraform/.ssh/id_rsa:ro
      - ${HOME}/.bash_history:/home/terraform/.ash_history:rw
    working_dir: /app
    # environment:
      # - AWS_DEFAULT_REGION=eu-west-1
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}